before_script:
  ##
  ## Run ssh-agent (inside the build environment)
  ##
  - eval `ssh-agent -s`
  ## - export
  ##
  ## Add the SSH key stored in PRIVATE_KEY variable to the agent store
  ## We're using tr to fix line endings which makes ed25519 keys work
  ## without extra base64 encoding.
  ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
  ##
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

# -------------------- #
# Compilation du Sujet #
# -------------------- #

deploiement:
  script:
    - export NAME
    - ./resources/binaries/build.sh
  tags:
    - marathon-23
  only:
    - main
